---
- name: Add MongoDB 4.2 apt key (Debian Buster)
  apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc
      state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB 4.2 repository (Debian Buster)
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main'
                  state=present
                  update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - install
    - mongodb    

- name: Disable kernel transparent huge-page defrag
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  copy:
    src: 99-thp-defrag.conf
    dest: /etc/sysfs.d/99-thp-defrag.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - mongodb
    - kernel

- name: Install MongoDB on Buster
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  apt:  
    pkg: [
      'mongodb-org',
      'mongodb-org-shell',
      'mongodb-org-server', 
      'mongodb-org-mongos'
    ]
    state: latest
  tags:
    - install
    - mongodb
    - deps  

- name: set mongodb_service fact for Debian
  when: ansible_distribution == "Debian"
  set_fact:
    mongodb_service: "mongod" 

- name: Make sure MongoDB is running
  service:  name={{ mongodb_service }}
            state=started
  tags:
    - install
    - mongodb
    - deps
    